### PR TITLE
Make display and framebuffer resolutions public

### PR DESCRIPTION
**Pull request by sebbert**

### CODE REVIEW

**Comment by yupferris** [comment]
Nice, but can I ask only the display resolution be made public?

A very tiny and super easy-to-miss detail of these values is that the system's framebuffers in VRAM are actually 256 pixels high rather than 224 pixels, yet only 224 pixels are displayed. For correctness we use the framebuffer res for storage, but the emu will only ever output the display res, so those are the only ones that should ever need to be public.

If it makes it more clear that there's a distinction feel free to separate the two sets by another newline if you'd like. :)

**Comment by sebbert** [comment]
Thanks for the quick clarification! Fixed now :) I was actually assuming `FRAMEBUFFER_RESOLUTION_*` was the correct one, may I suggest a name that makes this a little more explicit? E.g. `INTERNAL_RESOLUTION_*`. This might make no sense from the emulator side though

**Comment by yupferris** [comment]
How about `VRAM_FRAMEBUFFER_RESOLUTION` and `DISPLAY_RESOLUTION` ?

**Comment by sebbert** [comment]
Just a suggestion, I don't really mind as it's internal to the module. Now that I think about it, the access modifiers will in fact make the distinction clearer.

**Comment by yupferris** [comment]
Yeah, it's a good point though, just want to name it closer to what it is rather than by its visibility. Anyways, thanks for that, I'll go ahead and merge this :)

**Pull request merged**
